apiVersion: v2
name: observability

version: 60.2.0
appVersion: v0.74.0

dependencies:
  - name: kube-prometheus-stack
    version: 60.2.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: "6.60.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
