apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: worker-service
spec:
  template:
    metadata:
      labels:
        worker: service
      annotations:
        owner: "DevOps"
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: worker-service
      taints:
        - key: services
          effect: NoSchedule
      startupTaints: []
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t" ,"c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8", "16"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-1b", "ap-southeast-1c", "ap-southeast-1a"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
      kubelet:
        systemReserved:
          cpu: 200m
          memory: 400Mi
          ephemeral-storage: 1Gi
        kubeReserved:
          cpu: 200m
          memory: 400Mi
          ephemeral-storage: 1Gi
        evictionHard:
          memory.available: 3%
          nodefs.available: 15%
          nodefs.inodesFree: 5%
        evictionSoft:
          memory.available: 300Mi
          nodefs.available: 10%
          nodefs.inodesFree: 10%
        evictionSoftGracePeriod:
          memory.available: 1m
          nodefs.available: 1m30s
          nodefs.inodesFree: 2m

  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
