apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: worker-service
spec:
  amiFamily: Bottlerocket
  role: "Karpenter-cluster-dev-2024121414392788340000001c"
  subnetSelectorTerms:
    - id: subnet-03fbabb7a85656b88
    - id: subnet-0ebe7f506766976ef
    - id: subnet-04d289333f67dd2ed
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster-dev
  tags:
    Name: karpenter-worker-service
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        deleteOnTermination: true
