apiVersion: v2
name: loki

version: 5.35.0
appVersion: 2.9.2



dependencies:
  - name: loki
    condition: loki.enabled
    version: 5.35.0
    repository: https://grafana.github.io/helm-charts
  - name: "promtail"
    condition: promtail.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: 6.15.3
