service:
  serviceName: frontend
  migration:
    enabled: false
    command:
      - /bin/sh
      - -c
      - npm run migration:run
  revisionHistoryLimit: 1
  updateStrategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  podAnnotations:
    reloader.stakater.com/auto: "true"
  image:
    repository: 267583709295.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
    tag: v-15
    pullPolicy: IfNotPresent
  lifecycle: {}
  envFrom:
    - configMapRef:
        name: frontend-config
  serviceAccount:
    create: false
  podSecurityContext: {}
  securityContext: {}
  service:
    enabled: true
    type: ClusterIP
    port: 3000
    containerPort: 3000
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
  nodeSelector: {}
  tolerations: []
  livenessProbe: {}
  readinessProbe: {}
  configmap:
    enabled: true
    data:
      SERVER_URL: 'http://backend:3000/'
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: frontend
