{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env }}{{ .Values.serviceName }}-config
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | squote }}
  {{- end }}
{{- end }}
