{{- if .Values.externalsecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.serviceName }}
spec:
  refreshTime: "1m"
  externalSecretName: {{ .Values.env }}{{ .Values.serviceName }}-secret
  namespaceSelector:
    matchLabels: 
      external-secrets: enabled # kubectl label namespace <your-namespace> external-secrets=enabled
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: eks-secret-store
      kind: ClusterSecretStore
    target:
      name: {{ .Values.env }}{{ .Values.serviceName }}-secret
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: {{ .Values.externalsecret.name | default (printf "%s%s-secret" (.Values.env | default "") .Values.serviceName) }}
        decodingStrategy: Base64
{{- end }}
