{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "myservice.name" . }}-job
  labels:
    {{- include "myservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  annotations:
    helm.sh/hook: pre-install, pre-upgrade, pre-rollback
    helm.sh/hook-weight: "5"
spec:
  backoffLimit: {{ .Values.migration.retries }}
  template:
    metadata:
      name: {{ .Values.serviceName }}-job
      labels:
        {{- include "myservice.labels" . | nindent 8 }}
        app.kubernetes.io/component: job
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      restartPolicy: "OnFailure"
      serviceAccountName: {{ include "myservice.serviceAccountName" . }}
      containers:
        - name: {{ .Values.serviceName }}-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.migration.command }}
          command:
            {{- toYaml .Values.migration.command | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.migration.args }}
          args: {{ .Values.migration.args }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
