{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myservice.name" . }}
  labels:
    {{- include "myservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "http"
      protocol: TCP
      name: http
  {{- if .Values.additionalPorts }}
    {{- range .Values.additionalPorts }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort}}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "myservice.selectorLabels" . | nindent 4 }}
{{- end }}
