apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-frontend
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "70"
  namespace: dev
spec:
  rules:
    - host: frontend.chuong.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canary-frontend
                port:
                  name: http
  ingressClassName: ingress-nginx
